#FROM python:3.9-alpine
FROM python:3.8-slim
#RUN addgroup -S nonroot \
 #   && adduser -S nonroot -G nonroot

#USER nonroot

COPY requirements.txt .
RUN pip3 install -r requirements.txt

EXPOSE 80

WORKDIR app

COPY . /app

CMD ["python3" , "app.py"]


