name: Continuous Deployment

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  Preparation:
    name: Deployment of Docker Container
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull App Image
        run: docker pull ${{secrets.DOCKER_NAMESPACE}}/${{ secrets.DOCKER_REPOSITORY_NAME }}:master

      - name: Remove Already Running Container
        run: |
          export CONTAINER_NAME='ris_data_collection'
          bash stop_container.sh

      - name: Docker System Prune to Remove Old Images
        run: docker system prune -f

      - name: Run Docker Image to serve users
        run: |
          docker run --name=ris_data_collection -d \
          -e MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
          -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
          -e AZ_CONNECTION_STRING=${{ secrets.AZ_CONNECTION_STRING }} \
          -e AZ_ACCOUNT_KEY=${{ secrets.AZ_ACCOUNT_KEY }} \
          -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
          -e FILE_SHARE_NAME=${{ secrets.FILE_SHARE_NAME }} \
          -p 8080:8080 ${{secrets.DOCKER_NAMESPACE}}/${{ secrets.DOCKER_REPOSITORY_NAME }}:master