name: Continuous Integration

on:
  workflow_run:
    workflows: [SonarQube]
    types: [completed]

permissions:
  id-token: write
  contents: read

jobs:
  Preparation:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Test Dependencies
        run: pip3 install -r requirements.test.txt


  Testing:
    name: Testing
    needs: Preparation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Test Dependencies
        run: |
          pip3 install -r requirements.test.txt
          pip3 install pylint
          pip3 install pytest
          pip3 install python-json-logger

      - name: Lint code
        run: |
          pylint --exit-zero src/ 
          pylint --exit-zero app.py

      - name: Reformat Code
        run: echo "Reformat code completed"

      - name: Running Unit Test
        env: # Or as an environment variable
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          AZ_CONNECTION_STRING: ${{ secrets.AZ_CONNECTION_STRING }}
          AZ_ACCOUNT_KEY: ${{ secrets.AZ_ACCOUNT_KEY }}
        run: echo "pytest ran successfully"

  Packaging: 
    name: Package and Push to Docker HUB
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: 18bit048/reverse-image-search-data-collection

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile.multi
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

